apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: a9749d8750e934cd296565c8e0a19927-307358227.ap-south-1.elb.amazonaws.com.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wisecow-deployment
            port:
              number: 4499
  tls:
  - hosts:
    - a9749d8750e934cd296565c8e0a19927-307358227.ap-south-1.elb.amazonaws.com.sslip.io
    secretName: wisecow-tls
