apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: deny-shadow
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  file:
    matchPaths:
      - path: /etc/shadow
        action: Block
