apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}

