apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: wisecow
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

