name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: admin9010/wisecow:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
    - uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Create/Update TLS Secret
      env:
        TLS_CERT: ${{ secrets.TLS_CERT }}
        TLS_KEY: ${{ secrets.TLS_KEY }}
      run: |
        echo "$TLS_CERT" > tls.crt
        echo "$TLS_KEY" > tls.key
        kubectl create secret tls wisecow-tls-secret --cert=tls.crt --key=tls.key --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy K8s Manifests
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f k8s/

